name:                quartzlang
version:             0.1.0.0
github:              "githubuser/quartzlang"
license:             BSD3
author:              "Radosław Waśko"
maintainer:          "wasko.radek@gmail.com"
copyright:           "2019 Radosław Waśko"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/quartzlang#readme>

dependencies:
- base >= 4.7 && < 5
- array
- prettyprinter
- mtl
- containers
- union-find
- repline
- MissingH
- filepath
- directory

library:
  source-dirs: src

executables:
  quartzlang-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - quartzlang
